apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-archiver
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: archiver
            image: curlimages/curl:8.7.1
            command: ["/bin/sh", "-c"]
            args:
              - |
                TS=$(date +%Y%m%d-%H%M%S)
                DIR="/tmp/app-logs-$TS"
                mkdir -p $DIR
                
                IPS=$(nslookup log-app-discovery | grep "Address" | tail -n +2 | awk '{print $NF}')
                
                for IP in $IPS; do
                    CLEAN_IP=$(echo $IP | cut -d'#' -f1)
                    echo "Downloading logs from $CLEAN_IP..."
                    curl -s "http://$CLEAN_IP:8080/logs" > "$DIR/replica-$CLEAN_IP.log"
                  done
                
                tar -czf "/tmp/app-logs-$TS.tar.gz" -C /tmp "app-logs-$TS"
                echo "Archive created with logs from all replicas"
                ls -lh $DIR.tar.gz
                sleep 300
